#Question 2 (Plot 2)
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
my_data <- subset(data, Date %in% c("1/2/2007","2/2/2007"))
my_data$Date <- as.Date(my_data$Date, format = "%d/%m/%Y")
datetime <- paste(as.Date(my_data$Date), my_data$Time)
my_data$datetime <-as.POSIXct(datetime)
png(file="plot 2.png", width = 480, height = 480)
plot(my_data$Global_active_power~my_data$datetime, type = "l", xlab = "", ylab = "Global Active Power (Kilowatts)")
dev.off()