#Question 3 (Plot 3)
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
my_data <- subset(data, Date %in% c("1/2/2007","2/2/2007"))
my_data$Date <- as.Date(my_data$Date, format = "%d/%m/%Y")
datetime <- paste(as.Date(my_data$Date), my_data$Time)
my_data$datetime <-as.POSIXct(datetime)
png(file="plot 3.png", width = 480, height = 480)
plot(my_data$Sub_metering_1~my_data$datetime, type = "l", xlab = "", ylab = "Energy Sub Metering")
lines(my_data$Sub_metering_2~my_data$datetime, col = "red")
lines(my_data$Sub_metering_3~my_data$datetime, col = "blue")
legend("topright", lty = 1, lwd = 2, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()